woowa-techcamp-2022/android-banchan-01

app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailDataResponse.kt, app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt, app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt, app/src/main/java/co/kr/woowahan_banchan/domain/entity/history/HistoryItem.kt, app/src/main/java/co/kr/woowahan_banchan/domain/repository/HistoryRepository.kt
- #18 
- 최근 조회 내역 리스트 + 장바구니 리스트를 combine한 뒤, 리스트를 순회하며 hash 값으로 상세 정보 조회 API를 호출해 UI에 보여줄 타입의 리스트로 만들었습니다.
- 추가로, 장바구니에 담는 경우는 앱 여기저기서 반복해 쓰이는 것 같아 DishRepository에서 메서드를 하나 만들고 이를 UseCase로 분리해 재사용하는 것을 제안드립니다.
- Thank you Skipancho
close #18
=> [FEATURE] HistoryRepository 구현

app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderDao.kt, app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderItemDao.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSource.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSource.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSourceImpl.kt
- #26 
구현하면서 생각해보니 잘못된 부분이 있어 일부 수정했습니다.
- Flow로 리턴해서 얻을 수 있는 장점이 없다고 판단하였습니다.
=> [FEATURE] OrderDao, OrderItemDao 수정

app/src/main/java/co/kr/woowahan_banchan/data/database/dao/CartDao.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSource.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt, app/src/main/java/co/kr/woowahan_banchan/domain/usecase/CartAddUseCase.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
- #42 
기능을 구현한 뒤 App Inspection으로 확인하던 중 이런 상황이 발생하더라구요, Skipancho.
만일 내가 쭈꾸미 한돈 제육볶음을 1개를 장바구니에 추가한 뒤, (현재 DB상으로 쭈꾸미 한돈 제육볶음이 1개 있는 상황)
이어서 쭈꾸미 한돈 제육볶음을 2개를 장바구니에 추가한다면,
이 상황에서 나는 쭈꾸미 한돈 제육볶음 3개가 장바구니에 있어야 맞다고 생각합니다.
그런데 지금의 경우는 단순히 insertOrUpdateItems() 메서드를 호출하기 때문에 저 아이템이 이미 DB에 있어 insert가 아닌 update가 수행되어 실제로 장바구니에는 쭈꾸미 한돈 제육볶음 2개가 장바구니에 있습니다.
그래서 Dao에 특정 hash를 갖는 아이템의 수량을 가져오는 메서드를 추가한 뒤, Repository에서 다음과 같은 순서로 진행됩니다.
1. DB에 이 hash를 갖는 아이템이 몇 개 있는지 가져옴 (이를 편의상 `originalAmount` 라고 하겠습니다.)
2. 현재 내가 장바구니에 추가하고자 하는 아이템의 수량 (이를 편의상 `amount` 라고 하겠습니다.) 에 `originalAmount` 를 더한 값으로 DB에 갱신합니다.
3. 만일 이 hash를 가진 아이템이 DB에 없다면, getOrDefault 메서드를 사용해 `originalAmount` 는 0이 됩니다.
4. 즉, DB에 insertOrUpdateItem() 메서드를 호출하는 경우에는 `originalAmount + amount` 만큼의 수량이 담기게 됩니다.
새로 추가된 로직이기 때문에 이 부분까지 확인해 주시면 …
=> [FEATURE] 장바구니 추가 기능 구현

app/src/main/java/co/kr/woowahan_banchan/presentation/decoration/OrderListItemDecoration.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderlist/OrderListFragment.kt, app/src/main/java/co/kr/woowahan_banchan/util/ArgumentExtension.kt, app/src/main/java/co/kr/woowahan_banchan/util/ExtraExtension.kt, app/src/main/res/values/colors.xml
- #58 
이봐, @Skipancho !
자네는 Activity나 Fragment 간 데이터를 주고받을 때, Extra나 Argument를 사용하지 않나 ?
나는 매번 Activity와 Fragment 클래스 내 변수로 저 Extra나 Argument에서 꺼내와 값을 할당할 변수를 만드는 것을 매우 번거롭다고 생각해왔네.
예시를 들자면, 자네가 만들고있는 홈 화면에서 반찬을 누르면 내가 만든 반찬 상세 화면에 hash를 `putExtra("HASH", hash)` 처럼 넘겨줘야 하잖아?
나는 그럼 이럴 때마다 Activity 안에 `private var hash: String = ""` 이렇게 선언해두고
onCreate에서 `hash = intent.getStringExtra("HASH") ?: ""` 이렇게 해왔단 말일세 ...
불편하지 않은가? 그래서 가져왔다네. ExtraExtension과 ArgumentExtension !!
원리는 이렇다네. 집중해 Skipancho.
kotlin.properties의 ReadOnlyProperty를 가져와보겠네.
``` kotlin
/**
* Base interface that can be used for implementing property delegates of read-only properties.
*
* This is provided only for convenience; you don't have to extend this interface
* as long as your property delegate has methods with the same …
```
=> [FEATURE] ExtraExtension, ArgumentExtension 추가

app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderDetailUseCase.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/OrderActivity.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderlist/OrderListFragment.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderDetailViewModel.kt, app/src/main/res/layout/fragment_order_detail.xml, app/src/main/res/layout/item_order_detail.xml, app/src/main/res/values/colors.xml
- #58 
OrderDetail에는 이런 화면이 있는데, 쿠팡과 같은 단순 물품이 아닌 `식품` 주문 앱이라는 것을 감안했을 때, 주문 한 번에 과연 수십, 수백 개의 메뉴를 주문할까? 하는 생각이 들었어.
어쩌면 개발자의 오만한 판단일 수 있지만, 한 번에 20개가 넘는 반찬을 주문할 사람이 있을까?
1달치 반찬을 미리 배송시키는 사람이 있을까?
나는 없을 것 같다고 판단했고, 그래서 `RecyclerView`를 사용하지 않고 그냥 Item 레이아웃 xml 파일을 만들었네.
이를 inflate시켜 forEach를 통해 반복적으로 `LinearLayout에 addView` 하는 것이 더 효율적이라는 판단을 했어.
**ViewHolder가 재사용이 될 가능성이 적은데** RecyclerView를 사용하는 것이 과연 효과가 있을까?
RecyclerView가 `NestedScrollView` 안에 배치되어 있으면 ViewHolder를 재사용하는 것이 아니라, 다 만들어놓고 그저 스크롤되게 하기만 하는 것이라는 것은 금요일 데모 때 우리끼리 얘기한 것 같아.
그래서 주문 내역이 한 10개쯤 되어서 스크롤 될 것까지 생각했을 때, `NestedScrollView`도 사용하지 않고, RecyclerView를 쓰려면 ViewType을 나눠야 하는데 과연 꼭 그래야할까? 라는 생각이 들었어.
이런 근거로 그냥 동적으로 뷰 생성해서 레이아웃에 배치하는 코드로 작성했다네 !
혹시라도 뭔가 의견이 다르다면 꼭 의견 남겨줘 !
꼭 알려야 할 것 같은 일인데, 현재 Dao는 Order 테이블의 모든 아이템을 가져오는 메서드는 …
=> [FEATURE] 12_OrderDetail 화면 기초 기능 구현

app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt, app/src/main/java/co/kr/woowahan_banchan/domain/repository/CartRepository.kt, app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetCartItemCountUseCase.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
- #69 
close #69
To. Iceman (@hansh0101)
음.. 아이콘의 뱃지는 우선 BadgeDrawble과 BadgeUtils을 이용해서 구현을 했다네... 그와중@ExperimentalBadgeUtils 어노테이션이 필요하다는 경고를 보고 해당 API를 확인해보았지...
다음은 BadgeUtils에 대한 공식 문서의 첫 설명이네
>Utility class for [BadgeDrawable](https://developer.android.com/reference/com/google/android/material/badge/BadgeDrawable).
>
>Warning: This class is experimental and the APIs are subject to change.
아뿔싸... 언제 바뀌어도 이상하지 않은 실험적인 클래스라는군...
다른 방법으로 구현하는 것을 고려해야 할 듯 싶어
From. Skipancho (@Skipancho)
=> [FEATURE] 장바구니 아이콘에 Badge 추가

app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/OrderActivity.kt, app/src/main/res/layout/item_order_list.xml
- #73 
큰 건 없고, 주문내역 목록에서 텍스트가 위아래로 margin이 다른 것 같아 찝찝하여 Layout 하나를 감싸버렸다네.
close #73
=> [REFACTOR] #73 - 텍스트 위아래 정렬 맞추기

app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSource.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt, app/src/main/java/co/kr/woowahan_banchan/domain/repository/HistoryRepository.kt, app/src/main/java/co/kr/woowahan_banchan/domain/usecase/HistoryAddUseCase.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
- #75 
Skipancho, 일전에 이야기한 내용이 들어있네.
과연 View가 현재 시간을 꼭 ViewModel에 전달하는게 의미가 있을까? 그냥 바로 DataSource에서 시간을 계산해서 Dao에 넘겨주면 안 될까? 에 대해 말했던 내용이 기억나나?
이번 PR은 해당 내용이 담겨있네.
그럼, 이만!
=> [FEATURE] ProductDetailActivity에서 조회한 메뉴를 History 테이블에 저장

app/src/main/java/co/kr/woowahan_banchan/domain/entity/history/HistoryItem.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/RecentlyViewedAdapter.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/recentlyviewed/RecentlyViewedFragment.kt
- #78 
한 번 생각을 해보면 좋을 것 같은 주제가 있네... Skipancho.
CartAddBottomSheetd에서는 data 타입을 `Dish`로 하고 있더군.
과연 Dish라는 타입이 `일반적`인가? 라는 부분에 의문이 생기긴 했어.
BottomSheetDialog에서 필요한 데이터는 내가 분석했을 때, 이렇더라고.
> 화면에 보이는 것: ImageUrl, title(name), sPrice, nPrice
> 화면에 보이지 않는 것: hash
나머지 것들은 수량과, 수량에 따른 가격인데 이는 BottomSheetDialog 자체에서 처리할 수 있을 것 같았네.
실제로 UseCase에 전달하는 값은 `hash`, `amount`, `title` 이 3가지이고 말이야.
그렇다면 과연 BottomSheetDialog에 넘겨줄 데이터의 타입을 `Dish`로 하는게 좋을까? 라는 생각이 들었네.
내 제안은, BottomSheetDialog가 필요로 하는 데이터의 타입만을 쏙 뽑아내서 하나의 새로운 data class를 정의함이 어떻겠는가?
뭔가 추후 재사용과 확장에 더 용이할 것 같다는 생각을 했네.
일단은 내 `HistoryItem`을 `Dish`로 Mapping해주는 함수를 구현함으로 동작은 하도록 만들었네.
자네의 코딩 친구, Iceman이.
close #78
=> [FEATURE] RecentlyViewedFragment RecyclerView Item Click Event 처리

app/src/main/java/co/kr/woowahan_banchan/domain/entity/error/ErrorEntity.kt
- #105 
- `RetryableError`: 재시도할 가치가 있는 Exception. 사용자에게 재시도할지 말지 선택권을 제공(ex - Button)
- `ConditionalError`: 사용자의 환경이나 설정에 의한 Exception. 사용자에게 어떤 조치를 취한 뒤 재시도를 해보라고 조언
- `Unknown`: 개발자도 인지하지 못한 Exception. 추후 버그 리포트 때 해당 Exception을 분석해 해결하면 좋을 것 같음
=> [FEATURE] sealed class ErrorEntity 정의

app/src/main/java/co/kr/woowahan_banchan/data/classifier/ErrorClassifierImpl.kt, app/src/main/java/co/kr/woowahan_banchan/domain/classifier/ErrorClassifier.kt, app/src/main/java/co/kr/woowahan_banchan/domain/entity/error/ErrorEntity.kt
- #105 
- **ErrorEntity.RetryableError**: HttpRetryException, InterruptedIOException, InterruptedByTimeoutException, HttpException 중 timeout 관련
- **ErrorEntity.ConditionalError**: UnknownHostException
- **ErrorEntity.UnknownError**: IOException, else
아래는 공식문서 및 내부 코드를 참고한 내용일세.
재시도해서 성공할 것 같은 Exception들은 내가 판단하기에 이런 공통점이 있어.
1. Retry를 해야하는데 하지 못한 경우
2. Interrupt된 경우
3. TimeOut
또, ConditionalError로 판단한 UnknownHostException의 경우는 내가 종종 네트워크에 연결되지 않은 채로 빌드하면 생기는 Exception이더군. 추가로 더 찾아보니, 폐쇄망에 요청을 보내야 하는데 현재 연결된 네트워크는 해당 폐쇄망이 아닌 경우에 뜬다고도 하더군.
이외의 IOException이나 기타 Exception은 UnknownError로 처리했네.
<table style = "table-layout: auto; width: 100%; table-layout: fixed;">
<colgroup>
<col style="width:50%"/>
<col style="width:50%"/>
</colgroup>
<tr>
<td align="center">
Exception
</td>
<td …
=> [FEATURE] ErrorClassifer 인터페이스 및 구현체 구현

app/src/main/java/co/kr/woowahan_banchan/data/classifier/ErrorClassifierImpl.kt, app/src/main/java/co/kr/woowahan_banchan/domain/classifier/ErrorClassifier.kt, app/src/main/java/co/kr/woowahan_banchan/domain/entity/error/ErrorEntity.kt, app/src/main/java/co/kr/woowahan_banchan/domain/entity/result/CustomResult.kt
- #105 
기존의 Result에는 이런 companion object가 있다네.
> 
/**
* Companion object for [Result] class that contains its constructor functions
* [success] and [failure].
*/
public companion object {
/**
* Returns an instance that encapsulates the given [value] as successful value.
*/
@Suppress("INAPPLICABLE_JVM_NAME")
@InlineOnly
@JvmName("success")
public inline fun <T> success(value: T): Result<T> =
Result(value)
/**
* Returns an instance that encapsulates the given [Throwable] [exception] as failure.
*/
@Suppress("INAPPLICABLE_JVM_NAME")
@InlineOnly
@JvmName("failure")
public inline fun <T> failure(exception: Throwable): Result<T> =
Result(createFailure(exception))
}
오늘 논의한대로, 기존의 Result 클래스는 우리의 ErrorEntity를 failure로 받아들이지 못한다네. 왜냐면 Throwable을 받기 때문이지. 그래서 새로운 CustomResult를 추가했다네.
=> [FEATURE] sealed class CustomResult 추가

app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/best/BestDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/detail/DetailDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/maindish/MainDishDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/sidedish/SideDishDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/soupdish/SoupDishDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/ApiResponse.kt
=> [FEATURE] DataSource 리턴타입이 Flow가 아닌 메서드의 예외처리 방식을 runCatchingErrorEntity로 변경

app/src/main/java/co/kr/woowahan_banchan/data/extension/ErrorExtension.kt, app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt, app/src/main/java/co/kr/woowahan_banchan/domain/usecase/HistoryAddUseCase.kt, app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderDetailUseCase.kt, app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderListUseCase.kt, app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderTimeUseCase.kt, app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderUseCase.kt, app/src/main/java/co/kr/woowahan_banchan/domain/usecase/ProductDetailUseCase.kt, app/src/main/java/co/kr/woowahan_banchan/domain/usecase/UpdateCartItemsUseCase.kt
- #105 
이보게 @Skipancho , 예외처리 여정이 이제 거의 끝을 향해 가는 것 같아 보이네. (물론 아직 Flow에 대한 깊이 있는 예외처리는 하지 못했지만 말일세.)
최근 내 온 신경은 Error였다네. <s>(Error 모르겠다 ~)</s> 어떻게 DataSource에서 발생한 Error를 별도의 방해 혹은 간섭 혹은 왜곡 없이, Presentation까지 전달할 수 있을지에 대해 아주 끙끙 고민했던 것 같군. 특히 최근 3일간은 Error Handling에만 몰두했던 것 같네.
요약해서 말하자면, 그동안 `잘 만들었다`고 생각했던 `runCatchingErrorEntity`에는 내 치명적인 실수가 하나 있었네. 혹시 자네는 눈치챘는가? 아마도 자네도 눈치채지 못했을 것이야. 먼저 코드를 같이 봅세.
``` kotlin
inline fun <T, R> T.runCatchingErrorEntity(block: T.() -> R): Result<R> {
return try {
Result.success(block())
} catch (e: Throwable) {
val error = when (e) {
is HttpRetryException, is InterruptedIOException, is InterruptedByTimeoutException -> ErrorEntity.RetryableError
is UnknownHostException -> ErrorEntity.ConditionalError
is IOException -> ErrorEntity.UnknownError
is …
```
=> [FEATURE] UseCase의 리턴타입이 Flow가 아닌 메서드의 예외처리 방식을 runCatchingErrorEntity로 변경 및 runCatchingErrorEntity 내부 수정

app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImplTest.kt, app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImplTest.kt, app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImplTest.kt, app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSourceImplTest.kt
- #125 
@Skipancho , 테스트 코드란 무엇일까?
일단은 하던 작업을 마저 하고 나중에 수정을 하는 편이 나을 것 같아 먼저 PR을 날리네.
퇴근 직전 우리가 하던 대화이기도 하지만, 나는 Flow 관련 예외처리를 지금 throw만 하고 있다네.
그래서 뭔가 테스트 코드를 작성하면서 이상하다고 느꼈어.
나는 DataSourceImpl의 코드가 우리의 의도대로 동작하는지를 테스트하는 것인데, throw를 하는 메서드를 테스트하는 것이 맞는지에 대한 의문이 첫 번째이고,
두 번째는 우리가 정하기론 DataSource에서 발생한 에러를 우리의 에러 타입으로 분류해 Repository에 넘기기로 하지 않았나?
우리가 정한 것을 내가 어긴 것 같은 느낌을 지울 수 없네.
하지만 우선 하던 작업은 마무리한 뒤, 고치는 편이 나을 것이라 판단했네.
우리는 이미 git revert로 한 번 고생을 하지 않았나.
이 중요한 막판에 git이 꼬이는 것보다는, 차라리 내 코드를 수정해 다시 커밋하는 편이 낫다고 판단했네.
내가 오늘 밤에 한 번 어떻게 Flow에 대해 예외처리를 해야 적합한 것일지, 고민을 해보겠네.
자네도 의견이 생긴다면 바로바로 슬랙을 통해, 혹은 여기 코멘트를 통해 알려주게.
close #125
=> [FEATURE] LocalDataSourceImpl 테스트 코드 작성

app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt, app/src/test/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImplTest.kt, app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeCartDataSource.kt, app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeCartDataSourceWithError.kt, app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeDetailDataSource.kt, app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeDetailDataSourceWithError.kt
- #132 
close #132
To. 친애하는 Iceman (@hansh0101) 
우선은 진행한 CartRepository 구현체에 대한 테스트 코드를 PR을 날리겠네 
하루 밤 동안 내가 생각한 바로는 단순 throw만 하는 경우 우리는 어떤 에러를 날리겠다는 의도와 함수의 역할을 이미 정해둔 상황에서 그것이 throw를 잘 날리는가?를 테스트하는 것은 크게 의미가 없다는 생각이 들더군 
자네가 고민한 두 번째 고민은 에러타입을 분류해 Repository로 넘기는 것은 지금도 어느 정도 만족을 하고 있는 것 같다네. 나는 이 부분에서 의도와 역할에 조금 중점을 두고 생각했네, 
첫 번째. 우리의 의도는?
-> DataSource에서 또는 이전에서 발생한 에러를 우리가 정의한 에러 타입으로 분류
-> 분류한 에러타입을 Repository로 전달
두 번째. DataSource내의 함수들의 역할은?
-> 발생한 에러를 에러타입으로 분류한다. ( 이 부분은 toErrorEntity()가 해결 )
-> 분류한 에러타입을 Repository로 전달 ( throw를 이용해 호출부(Repository)로 에러를 전달)
여기서의 문제는 굳이 Repository에서 throw를 잡아내야하는가? 정도일 것 같군
계속 생각이 왔다갔다 하는 중이네만
뭐 지금 시점에서 드는 생각은 이러하네
1. data layer에서 throw를 모두 잡아서 유형만 전달.
2. domain, ui에서는 data 관련 Exception이 추가적으로 생기면 안된다. 그것은 코드의 오류
3. Repository 구현체는 data layer
4. …
=> [FEATURE] CartRepository Test Code 작성

app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSource.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt, app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImplTest.kt, app/src/test/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImplTest.kt, app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeHistoryDataSource.kt, app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeHistoryDataSourceWithError.kt
- #140 
이보게 @Skipancho , 이미 내가 슬랙을 통해 공유하긴 했다만, 나 스스로 이해가 되지 않는 점이 있어 이렇게 글을 남기네.
그동안 우리는, runTest {} 로 TestScope을 열고 그 안에서 각종 suspend function을 처리하지 않았나?
그리고 Flow의 경우는 그 TestScope 안에서 launch를 통해 `UnconfinedTestDispatcher`를 사용해 Flow를 collect해왔지.
근데 이상하게도 HistoryRepository에서는 이렇게 했을 때, 문제가 발생하더군.
에러 내용은 아래와 같다네.
> java.lang.IllegalStateException: Detected use of different schedulers. If you need to use several test coroutine dispatchers, create one `TestCoroutineScheduler` and pass it to each of them.
다른 스케줄러를 사용한 것 같고, 여러 코루틴 디스패처를 사용해야 한다면 하나의 `TestCoroutineScheduler`를 만들고 그것을 각각에 전달하라는 이야기로 이해했네.
그런데 그동안의 우리 테스트 코드에서는 왜 이런 문제가 발생하지 않았을까? 왜 갑자기 지금에서야 문제가 발생할까?
나는 이와 관련해 자료를 찾던 중, https://developer.android.com/kotlin/coroutines/test#unconfinedtestdispatcher 를 참고할 수 있었네.
이 링크에 보면, 애초에 …
=> [FEATURE] HistoryRepository 테스트 코드 작성 및 HistoryDataSource Flow 예외처리 방식 변경

app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
=> [FEATURE] ProductDetailActivity UiStates, UiEvents 적용

app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderlist/OrderListFragment.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderListViewModel.kt
=> [FEATURE] OrderListFragment UiStates, UiEvents 적용

app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
- #199 
요구사항이 10개 이상일 경우 10+로 나타내라고 하지만 왜 10+를 해야하는지 잘 모르겠네, 이렇게 바꾸는 이유는 숫자의 텍스트 길이를 더이상 늘리지 않는 것에 있다고 생각을 하네, 그렇지만 10+는 99보다 길이가 더 길지 않나? 그렇다면 10+가 99로 텍스트를 치는 것 보다 좋은 것이 전혀 없다고 생각을 하네 그렇기 때문에 9+가 되도록 수정했다네
close #199
=> [FIX] 카트 개수가 10개 이상이 되면 9+가 되도록 수정

app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
- #200 
close #200
이 부분은 음 CartFragment에서 HistoryFragment로 이동할 시 CartFragment의 onDestroy가 호출되지 않아 viewModel이 계속 살아있다는 것을 간과했네, 그래서 계속 originalCart에 갱신된 장바구니 목록이 추가되고 있었던거야... OrderUseCase에서는 originalCart를 기준으로 주문과 갱신을 하기 때문에 중복되어 주문이 들어가는 현상이 일어났던 것으로 추측하네 이 문제는 originalCart가 갱신될때 해당 리스트를 clear하는 것으로 해결했다네
=> [FIX] 장바구니 화면에서 최근 본 화면으로 넘어가 장바구니를 추가하게 되면 주문이 중복되는 오류 수정

app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/BestViewModel.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/MainDishViewModel.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/OtherDishViewModel.kt, app/src/main/java/co/kr/woowahan_banchan/util/ImageLoader.kt
- #206 
원인을 파악했네. 왜 에러 다이얼로그가 여러 번 뜨는지 말일세.
ViewPager2의 경우 Fragment가 onDestroy되지 않는 사실을 아는가? 여기서 바로 문제가 시작되는 것이었어.
우리는 Cart 데이터를 Flow로 collect하고 있는데, Fragment가 onStop조차 들어가지 않기 때문에 ViewModel이 죽지 않았고, 그래서 계속 collect가 되면서 네트워크 요청을 레포지토리에서 하기 때문에 에러가 4번 났다고 파악하는 것이었어.
그래서 onPause에서 ViewModel의 collect를 취소하도록 했네. 그리고 onResume에서 다시 collect를 하도록 처리했네. 우리의 `빨대` 비유를 생각하면서 말이야.
close #206
=> [FIX] 네트워크 연결 해제 상태에서 에러 다이얼로그가 여러 번 표시되는 오류

app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartActivity.kt, app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
- #203 
Fragment BackStackCount만으론 문제를 해결할 수 없어서, 난 이렇게 처리했다네.
OrderDetailFragment로 replace할 때, 클래스명으로 태그를 붙이는거지. 그리고 이 태그로 Fragment가 존재하는지 여부를 `findFragmentByTag`로 체크해서, 이 값을 `onSaveInstanceState`의 `outState`에 putBoolean으로 전달하는 것이네.
생각보다 쉽게 해결한 듯 하구만. 하하하
close #203
=> [FIX] 장바구니 화면에서 주문 후 화면 회전 시 화면 유지되지 않는 오류

app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/best/BestDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/detail/DetailDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/maindish/MainDishDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/sidedish/SideDishDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/soupdish/SoupDishDataSourceImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt, app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt, app/src/main/java/co/kr/woowahan_banchan/di/ApiModule.kt, app/src/main/java/co/kr/woowahan_banchan/di/DataSourceModule.kt, app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt, app/src/main/res/layout/activity_product_detail.xml
- #195 
**`ApiModule`**, **`DatabaseModule`** 의 경우 각각 Retrofit, Room에 대한 의존성을 갖는 `Service`, `Dao`와 연관되기 때문에, @Binds로 구현할 수 없었네. 왜냐면 해당 인터페이스의 구현체를 넘겨줄 수 없었거든.
하지만 **`DataSourceModule`**, **`RepositoryModule`**은 달랐네. 우리가 정의한 인터페이스이고, 우리가 구현한 구현체기 때문이야. 그래서 @Binds 로 구현을 변경했네. @Binds 를 사용했을 때 @Provides를 사용한 경우보다 코드가 더 간결해진 것 같아 좋더군. 하지만 내부적으로 조금 더 딥 다이브 해볼 필요는 느꼈네. 뭔가 그냥 코드만 봤을 때, 더 간결하다는 느낌은 받긴 했네.
close #195
=> [REFACTOR] Hilt @Binds, @Provides 리팩토링
