woowa-techcamp-2022/android-banchan-01

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/co/kr/woowahan_banchan/application/BanchanApplication.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/MainActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/base/BaseActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/base/BaseFragment.kt
- app/src/main/res/layout/activity_main.xml
- build.gradle
> [CHORE] Dependency 세팅 + BaseClass 구현

- app/build.gradle
- app/src/main/AndroidManifest.xml
- build.gradle
> [CHORE] Dependency 추가(retrofit, okhttp) + Permission 추가 (Internet)

- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/BanchanDatabase.kt
- app/src/main/java/co/kr/woowahan_banchan/data/model/local/CartDto.kt
- app/src/main/java/co/kr/woowahan_banchan/data/model/local/HistoryDto.kt
- app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderDto.kt
- app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderItemDto.kt
> [FEATURE] Database 초기 구현 - Local Dto 추가

- app/src/main/java/co/kr/woowahan_banchan/data/api/BestService.kt
- app/src/main/java/co/kr/woowahan_banchan/data/api/DetailService.kt
- app/src/main/java/co/kr/woowahan_banchan/data/api/MainDishService.kt
- app/src/main/java/co/kr/woowahan_banchan/data/api/SideDishService.kt
- app/src/main/java/co/kr/woowahan_banchan/data/api/SoupDishService.kt
- app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/ApiResponse.kt
- app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/BestResponse.kt
- app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailDataResponse.kt
- app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailResponse.kt
- app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DishResponse.kt
> [FEATURE] Remote Api Service 인터페이스 + Response 데이터 클래스 구현

- app/src/main/java/co/kr/woowahan_banchan/di/CoroutineModule.kt
> [FEATURE] CoroutineModule 구현

- app/build.gradle
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/best/BestDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/best/BestDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/detail/DetailDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/detail/DetailDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/maindish/MainDishDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/maindish/MainDishDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/sidedish/SideDishDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/sidedish/SideDishDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/soupdish/SoupDishDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/remote/soupdish/SoupDishDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/di/ApiModule.kt
> [FEATURE] Remote DataSource 구현 + ApiModule 구현

- app/src/main/java/co/kr/woowahan_banchan/data/database/BanchanDatabase.kt
- app/src/main/java/co/kr/woowahan_banchan/data/database/dao/CartDao.kt
- app/src/main/java/co/kr/woowahan_banchan/data/database/dao/HistoryDao.kt
- app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderDao.kt
- app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderItemDao.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/model/local/CartDto.kt
- app/src/main/java/co/kr/woowahan_banchan/data/model/local/HistoryDto.kt
- app/src/main/java/co/kr/woowahan_banchan/di/DataSourceModule.kt
- app/src/main/java/co/kr/woowahan_banchan/di/DatabaseModule.kt
> [FEATURE] Local DataSource 구현

- app/src/main/java/co/kr/woowahan_banchan/di/DataSourceModule.kt
> [FEATURE] RemoteDataSourceModule 구현

- app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DishResponse.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/di/DataSourceModule.kt
- app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/entity/dish/BestItem.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/entity/dish/Dish.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/DishRepository.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
- #15 
- 장바구니 담았는지 여부 정보를 포함한 기획전(BestItem) 리스트 조회 API 연결
- 장바구니에 메뉴를 추가하는 API 연결
Thanks to. Skipancho
From. Iceman
> [FEATURE] DishRepository 내 BestDataSource 연결

- app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/DishRepository.kt
- #15 
- Shout out to Iceman🧊
close #15
> [FEATURE]  getDishes 메소드 구현

- app/src/main/java/co/kr/woowahan_banchan/data/database/dao/HistoryDao.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt
> [FEATURE] 최근 내역 조회 미리보기(최대 7개 표시) 메서드 구현

- app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailDataResponse.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/DetailRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/entity/detail/DishInfo.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/DetailRepository.kt
> [FEATURE] DetailRepository 구현

- app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderItemDao.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/orderitem/OrderItemDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderDto.kt
- app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderItemDto.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/entity/orderhistory/OrderHistory.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/entity/orderhistory/OrderItem.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/OrderHistoryRepository.kt
> [FEATURE] OrderHistoryRepository 구현

- app/src/main/AndroidManifest.xml
- app/src/main/java/co/kr/woowahan_banchan/util/ImageLoader.kt
> [FEATURE] ImageLoader 구현

- app/src/main/AndroidManifest.xml
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/base/BaseActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/base/BaseFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
> [MOVE] presentation 패키지 구조화

- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
> [CHORE] color, theme 수정

- app/src/main/res/drawable/bg_default_tab.xml
- app/src/main/res/drawable/bg_loading_dialog.xml
- app/src/main/res/drawable/bg_selected_tab.xml
- app/src/main/res/drawable/circle.xml
- app/src/main/res/drawable/ic_minus.xml
- app/src/main/res/drawable/ic_plus.xml
- app/src/main/res/drawable/selector_product_detail_indicator.xml
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
> [FEATURE] 9_Product_Detail 화면 관련 color, theme, drawable 추가

- app/src/main/java/co/kr/woowahan_banchan/domain/entity/dish/Dish.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetBestsUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/BestItemAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/DishAdapter.kt
- app/src/main/res/drawable/rectangle_radius_999.xml
- app/src/main/res/layout/item_best.xml
- app/src/main/res/layout/item_dish.xml
> [FEATURE] Home 화면 관련 UseCase 및 Adapter 구현

- app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailDataResponse.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/entity/detail/DishInfo.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/ProductDetailUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/util/ContextUtil.kt
- app/src/main/java/co/kr/woowahan_banchan/util/IntExtension.kt
> [FEATURE] 9_Product Detail 화면 관련 domain, data, util 파일 구현 및 수정

- app/src/main/AndroidManifest.xml
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/ProductDetailViewPagerAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/LoadingDialog.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
- app/src/main/res/drawable/strike_through.xml
- app/src/main/res/layout/activity_product_detail.xml
- app/src/main/res/layout/dialog_loading.xml
- app/src/main/res/layout/item_product_detail.xml
> [FEATURE] 9_Product Detail 화면 presentation 

- app/src/main/java/co/kr/woowahan_banchan/domain/entity/dish/Dish.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/BestItemAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/DishAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/ViewPagerAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
- app/src/main/res/drawable/ic_cart_btn.xml
- app/src/main/res/drawable/ic_cart_btn_added.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_best.xml
- app/src/main/res/layout/fragment_maindish.xml
- app/src/main/res/layout/item_best.xml
- app/src/main/res/layout/item_dish.xml
- app/src/main/res/menu/menu_app_bar.xml
> [FEATURE] 1_Home 화면 UI 구현

- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
> [FEATURE] BestFragment-ProductDetailActivity 연결

- app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/CartRepository.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/DishRepository.kt
> [FEATURE] 기존 DishRepository에 있던 장바구니에 담는 기능을 CartRepository를 새로 생성해 이전

- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/util/ImageLoader.kt
> [REFACTOR] 코드 리뷰 반영 - ImageLoader , BestFragment

- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddDialog.kt
- app/src/main/res/drawable/bg_alert_dialog.xml
- app/src/main/res/drawable/inset_horizontal_24.xml
- app/src/main/res/layout/dialog_cart_add.xml
- #42 
CartAddDialog(context).show() 하기만 하면 되고, 추후 "장바구니 확인" 클릭 시 장바구니 화면으로 이동시키면 될 것 같습니다, Skipancho
close #42
> [FEATURE] 장바구니 추가 성공 시 표시되는 Dialog 구현

- app/src/main/AndroidManifest.xml
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/OrderActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderlist/OrderListFragment.kt
- app/src/main/res/layout/activity_order.xml
- app/src/main/res/layout/fragment_order_list.xml
- app/src/main/res/layout/item_order_list.xml
> [FEATURE] OrderListFragment UI initView() 구현

- app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderDao.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderListUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/OrderActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderlist/OrderListFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/UiState.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderListViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/util/IntExtension.kt
- app/src/main/java/co/kr/woowahan_banchan/util/NumberExtension.kt
- app/src/main/res/layout/fragment_order_list.xml
- app/src/main/res/layout/item_order_list.xml
- app/src/main/res/values/colors.xml
> [FEATURE] OrderListFragment-주문내역 조회 API 연결

- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetDishesUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/BestItemAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/DishAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/FilterSpinnerAdapter.kt
- app/src/main/res/layout/item_best.xml
- app/src/main/res/layout/item_dish_grid.xml
- app/src/main/res/layout/item_dish_linear.xml
- app/src/main/res/layout/item_filter.xml
> [FEATURE] 2_Maindish 화면 관련 UseCase 및 Adapter 구현

- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/OrderActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderlist/OrderListFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/util/NumberExtension.kt
- app/src/main/java/co/kr/woowahan_banchan/util/OrderListItemDecoration.kt
- app/src/main/res/layout/item_order_list.xml
> [FEATURE] OrderListFragment RecyclerView ItemDecoration 적용

- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/ViewPagerAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/sidedish/SideDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/soupdish/SoupDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/MainDishViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/SoupDishViewModel.kt
- app/src/main/res/layout/fragment_side_dish.xml
- app/src/main/res/layout/fragment_soup_dish.xml
- app/src/main/res/layout/item_dish_grid.xml
- app/src/main/res/layout/item_dish_linear.xml
- app/src/main/res/values/strings.xml
- #56 
이보게 Iceman(@hansh0101) 큰 작업이 아니었음에도 시간을 많이 끌어 미안하네, RecyclerView의 아이템 이미지 사이즈가 고정값을 가지고 있는 것 보단 화면에 따라서 조절을 하는 것이 맞다고 생각되어서 수정을 했다네 그런데 아뿔싸...그 과정에서 기획전 화면의 아이템 이미지(soup 화면과 아이템 view를 공유하는)가 화면을 꽉채우는 문제가 발생해버렸네... 조만간 기획전 화면을 수정을 할 예정이라 일단 그대로 놔 두었네...
close #56
> [FEATURE] 3_Soup 화면 구현

- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddBottomSheet.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/bottomsheet/BottomSheetViewModel.kt
- app/src/main/res/layout/dialog_cart_add_bottom.xml
- app/src/main/res/values/themes.xml
> [FEATURE] BottomSheet UI 구현

- app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderDao.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/OrderHistoryRepository.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderTimeUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderDetailViewModel.kt
> [FEATURE] 12_OrderDetail 화면 구현

- app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderDao.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/OrderHistoryRepository.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderTimeUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/OrderActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderlist/OrderListFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderDetailViewModel.kt
- app/src/main/res/menu/menu_order.xml
- #58 
루터회관에서 급하게 퇴근하느라 PR 2개로 나누는 게 좋은 것 같은데 문제는 이제 이게 PR을 분리하는 것이 맞다는 판단이 들어서 ... 그래서 급하게 push한 감이 있네.
직전 PR이랑 겹치는 부분은 제외하고, Toolbar 관련 코드만 봐주면 좋을 것 같네 !
close #58
> [FEATURE] 

- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/BestItemAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/DishAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddBottomSheet.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/bottomsheet/BottomSheetViewModel.kt
- app/src/main/res/layout/dialog_cart_add_bottom.xml
> [FEATURE] BottomSheet 이벤트 적용

- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetBestsUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/BestItemAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/decoration/HorizontalItemDecoration.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/decoration/HorizontalLayoutManager.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/listener/TouchInterceptorListener.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
- app/src/main/res/layout/fragment_best.xml
- app/src/main/res/layout/item_best.xml
- app/src/main/res/layout/item_best_header.xml
> [REFACTOR] 1_Home 화면 수정

- app/src/main/AndroidManifest.xml
- app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailDataResponse.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/RecentlyViewedUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/RecentlyViewedAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/recentlyviewed/RecentlyViewedFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/RecentlyViewedViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/util/NumberExtension.kt
- app/src/main/res/layout/activity_cart.xml
- app/src/main/res/layout/fragment_recently_viewed.xml
- app/src/main/res/layout/item_recently_viewed.xml
- #75 
- RecyclerView에 ItemDecoration을 통해 아이템 간 간격을 지정할 필요가 있고,
- RecyclerView 아이템에서 장바구니 버튼을 통해 장바구니에 추가할 수 있게 연결해야 하며,
- RecyclerView 아이템을 클릭할 경우 해당 아이템에 대한 상세화면으로 이동하는 것이 좋을 것 같습니다.
위 작업은 별도의 이슈로 처리하면 더 좋을 것 같다고 생각하네, Skipancho.
아직 저 부분은 미완성이라는 사실, 알고 있으면 좋을 것 같구만 ! 그럼 이만.
close #75
> [FEATURE] 16_RecentlyViewedProducts 화면 구현

- app/src/main/java/co/kr/woowahan_banchan/presentation/decoration/GridItemDecoration.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/recentlyviewed/RecentlyViewedFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
- app/src/main/res/layout/fragment_recently_viewed.xml
> [FEATURE] RecentlyViewedFragment RecyclerView ItemDecoration 적용

- app/src/main/java/co/kr/woowahan_banchan/domain/entity/dish/SelectedDish.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/entity/history/HistoryItem.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/recentlyviewed/RecentlyViewedFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddBottomSheet.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/bottomsheet/BottomSheetViewModel.kt
> [REFACTOR]  BottomSheetDialog용 데이터 타입 분리

- app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderDao.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/OrderHistoryRepository.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/LatestOrderTimeUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/UiState.kt
> [FEATURE] 홈 화면 상단 프로필 아이콘에 현재 배송중인 상품이 있는 경우 아이콘 변경

- app/src/main/java/co/kr/woowahan_banchan/domain/entity/cart/CartItem.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/CartAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
- app/src/main/res/drawable/ic_minus_12.xml
- app/src/main/res/drawable/ic_plus_12.xml
- app/src/main/res/layout/fragment_cart.xml
- app/src/main/res/layout/item_cart.xml
- app/src/main/res/layout/layout_cart_info.xml
- app/src/main/res/layout/layout_cart_recently_viewed.xml
> [FEATURE] 11_Cart 화면 UI 구현

- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
> [FIX] 최근 주문 내역의 주문시간 조회 API 수정

- app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailDataResponse.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/di/RepositoryModule.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/CartRepository.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/DeleteCartItemsUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetCartItemsUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/UpdateCartItemsUseCase.kt
> [FEATURE]  장바구니 관련 UseCase 추가

- app/src/main/java/co/kr/woowahan_banchan/domain/entity/cart/CartItem.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/CartAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
- app/src/main/res/drawable/selector_btn_bg.xml
- app/src/main/res/drawable/strike_through.xml
- app/src/main/res/layout/fragment_cart.xml
- app/src/main/res/layout/item_cart.xml
- app/src/main/res/layout/layout_cart_info.xml
- app/src/main/res/layout/layout_cart_recently_viewed.xml
> [FEATURE] 11_Cart 화면 버튼 이벤트 및 주문하기 구현

- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/OrderUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/UpdateCartItemsUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/CartAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/RecentlyViewedAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddDialog.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
> [FEATURE] 장바구니에서 변화가 있는 아이템만 데이터베이스에 업데이트 하도록 수정

- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/CartAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/NumberPickerDialog.kt
- app/src/main/res/layout/dialog_number_picker.xml
> [FEATURE] NumberPickerDialog 구현 및 적용

- app/src/main/AndroidManifest.xml
- app/src/main/java/co/kr/woowahan_banchan/presentation/notification/AlarmReceiver.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderDetailViewModel.kt
> [FEATURE] 주문 20분 후 Notification 구현

- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/CartAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
- app/src/main/res/layout/fragment_best.xml
- app/src/main/res/layout/fragment_cart.xml
> [FEATURE]  장바구니 아이템 선택 삭제 기능 구현

- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/FilterSpinner.kt
- app/src/main/res/drawable/bg_spinner_openned.xml
- app/src/main/res/layout/fragment_main_dish.xml
- app/src/main/res/layout/fragment_other_dish.xml
> [FEATURE] Spinner 화살표 전환 구현

- app/src/main/java/co/kr/woowahan_banchan/domain/entity/dish/Dish.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/entity/history/HistoryItem.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/BestItemAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/CartAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/DishAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/ViewPagerAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/recentlyviewed/RecentlyViewedFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/BestViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/MainDishViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/OtherDishViewModel.kt
> [REFACTOR] job을 반환하는 함수 제거 + View에서 domain Import 제거

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/co/kr/woowahan_banchan/application/BanchanApplication.kt
- app/src/main/java/co/kr/woowahan_banchan/data/database/dao/CartDao.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/worker/CartUpdateWorker.kt
- app/src/main/java/co/kr/woowahan_banchan/util/SerializeUtil.kt
- #115 
우선은 기존 로직 안에서 CoroutinScope로 작동시키던 부분을 WorkManager로 교체만 해두었다네 
추후 에러핸들링을 적용시키면 될 것 같아
아 추가적으로 CartDao에서 getItems에 정렬을 추가했다네 그 이유는 음... 장바구니 목록이 갱신이 되면 목록의 순서가 바뀌는데 
사용자의 입장에서 보았을 때 장바구니 목록의 순서가 바뀌는 것은 제법 불편할 것 같다는 생각이 들더군 
그래서 우선의 PK값인 hash를 기준으로 정렬하도록 해두었네
close #115
> [FEATURE] 장바구니 갱신 WorkManager 적용 

- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddBottomSheet.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/ErrorDialog.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/UiModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/bottomsheet/BottomSheetViewModel.kt
- #105 
<image src="https://user-images.githubusercontent.com/81508084/185760209-e39e5c55-198a-4b7e-b06d-53a364fce1f1.png" width="33%"/><image src="https://user-images.githubusercontent.com/81508084/185760217-7b573779-1491-4942-a070-d16d2ac13820.png" width="33%"/><image src="https://user-images.githubusercontent.com/81508084/185760224-d4731963-b1aa-4a49-8a5c-64103d8ef75c.png" width="33%"/>
@Skipancho , 자네 생각이 궁금하네.
엥? 을 인터넷 연결 오류에 넣고, 헉! 을 재시도 가능 오류에 넣는 게 더 좋을 것 같은가?
> [FEATURE] Error 발생 시 UiEvent + SharedFlow로 Feedback 제공

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/co/kr/woowahan_banchan/application/BanchanApplication.kt
- app/src/main/java/co/kr/woowahan_banchan/data/database/dao/CartDao.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/worker/CartUpdateWorker.kt
- app/src/main/java/co/kr/woowahan_banchan/util/SerializeUtil.kt
> [Git 복구작업]

- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/history/HistoryDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/extension/ErrorExtension.kt
> [FEATURE] DataSource Flow 예외처리 구현

- app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/CartRepository.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/DishRepository.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/HistoryRepository.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/OrderHistoryRepository.kt
> [FEATURE] Repository Flow 예외처리 구현

- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetBestsUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetCartItemCountUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetCartItemsUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/GetDishesUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/LatestOrderTimeUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/RecentlyViewedUseCase.kt
> [FEATURE] UseCase Flow 예외처리 구현

- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/RecentlyViewedViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/BestViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/MainDishViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/OtherDishViewModel.kt
> [FEATURE] ViewModel Flow 예외처리 구현

- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
- app/src/main/res/layout/activity_product_detail.xml
> [FEATURE] 9_ProductDetail 화면 Toolbar 추가

- app/src/test/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImplTest.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeBestDataSource.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeMainDishDataSource.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeSideDishDataSource.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeSoupDishDataSource.kt
> [FEATURE] DishRepository Test Code 작성

- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
- app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImplTest.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/FakeOrderDataSource.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/FakeOrderItemDataSource.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImplTest.kt
> [FEATURE] DataSource Flow 예외처리 방식 수정 및 OrderHistoryRepository 테스트 코드 작성

- app/src/test/java/co/kr/woowahan_banchan/data/repository/FakeOrderDataSourceWithError.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/FakeOrderItemDataSourceWithError.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImplTest.kt
> [FEATURE] OrderHistoryRepository 예외 상황에 대한 테스트 코드 작성

- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImpl.kt
- app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/cart/CartDataSourceImplTest.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeCartDataSource.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeCartDataSourceWithError.kt
> [REFACTOR] CartDataSource, Result로 에러 타입을 전달하도록 수정 

- app/src/test/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImplTest.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeOrderDataSource.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeOrderDataSourceWithError.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeOrderItemDataSource.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeOrderItemDataSourceWithError.kt
> [MOVE] FakeDataSource 패키지 이동

- app/src/test/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImplTest.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeBestDataSourceWithError.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeMainDishDataSourceWithError.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeSideDishDataSourceWithError.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/FakeSoupDishDataSourceWithError.kt
> [FEATURE] CartRepository 에러 테스트 코드 작성

- app/src/test/java/co/kr/woowahan_banchan/data/repository/DetailRepositoryImplTest.kt
> [FEATURE] DetailRepository Test Code 작성

- app/src/test/java/co/kr/woowahan_banchan/data/repository/HistoryRepositoryImplTest.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImplTest.kt
> [REFACTOR] testDispatcher 관련 코드 리팩토링

- app/build.gradle
- app/src/main/java/co/kr/woowahan_banchan/data/database/BanchanDatabase.kt
- app/src/main/java/co/kr/woowahan_banchan/data/database/Migration.kt
- app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderDto.kt
- app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderItemDto.kt
- app/src/main/java/co/kr/woowahan_banchan/di/DatabaseModule.kt
> [FEATURE] Order Dto Column 추가 및 Room DataBase Migration

- app/src/main/java/co/kr/woowahan_banchan/data/model/remote/response/DetailDataResponse.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/CartAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/DishAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/ProductDetailViewPagerAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/RecentlyViewedAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddBottomSheet.kt
- app/src/main/java/co/kr/woowahan_banchan/util/ImageLoader.kt
> [FEATURE] ImageLoader 개선 및 PlaceHolder 구현 

- app/.gitignore
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderDetailViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
> [FEATURE] OrderDetailFragment UiStates, UiEvents 적용

- app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderDao.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/entity/orderhistory/OrderHistory.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/OrderHistoryRepository.kt
- app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImplTest.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/local/order/FakeOrderDataSource.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/local/order/FakeOrderDataSourceWithError.kt
> [FEATURE] OrderHistoryRepository 및 OrderDatasource, 주문 완료 정보 업데이트 함수 추가

- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/CheckOrderCompleteUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
> [FEATURE] 주문 완료 정보 불러오기 구현

- app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/history/HistoryFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/ErrorDialog.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/BestViewModel.kt
> [FEATURE] BestFragment UiStates, UiEvents 적용

- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/MainDishViewModel.kt
> [FEATURE] MainDishFragment UiStates, UiEvents 적용

- app/src/main/java/co/kr/woowahan_banchan/data/database/dao/OrderDao.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSource.kt
- app/src/main/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/repository/OrderHistoryRepository.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/usecase/UpdateOrderUseCase.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/notification/AlarmReceiver.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/worker/OrderUpdateWorker.kt
> [FEATURE] 주문 완료 업데이트 기능 구현

- app/src/main/java/co/kr/woowahan_banchan/data/repository/DishRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/OtherDishViewModel.kt
- app/src/main/res/layout/fragment_other_dish.xml
> [FEATURE] OtherDishFragment UiStates, UiEvents 적용

- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddBottomSheet.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/bottomsheet/BottomSheetViewModel.kt
> [FEATURE] CartAddBottomSheet UiStates, UiEvents 적용

- app/src/test/java/co/kr/woowahan_banchan/data/datasource/local/order/OrderDataSourceImplTest.kt
- app/src/test/java/co/kr/woowahan_banchan/data/datasource/remote/best/BestDataSourceImplTest.kt
- app/src/test/java/co/kr/woowahan_banchan/data/datasource/remote/detail/DetailDataSourceImplTest.kt
- app/src/test/java/co/kr/woowahan_banchan/data/datasource/remote/maindish/MainDishDataSourceImplTest.kt
- app/src/test/java/co/kr/woowahan_banchan/data/datasource/remote/sidedish/SideDishDataSourceImplTest.kt
- app/src/test/java/co/kr/woowahan_banchan/data/datasource/remote/soupdish/SoupDishDataSourceImplTest.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/OrderHistoryRepositoryImplTest.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/local/order/FakeOrderDataSource.kt
- app/src/test/java/co/kr/woowahan_banchan/data/repository/fakedatasource/local/order/FakeOrderDataSourceWithError.kt
> [FEATURE] OrderDao, OrderDataSource, OrderRepository 변경에 따른 Test Code 추가

- app/src/main/java/co/kr/woowahan_banchan/data/repository/CartRepositoryImpl.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/UiState.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
- #186 
드디어 UiState 이전 작업을 끝마쳤다네.
close #186
> [FEATURE] CartFragment UiStates, UiEvents 적용

- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/history/HistoryFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/MainActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/best/BestFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/maindish/MainDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/main/otherdish/OtherDishFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderlist/OrderListFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/productdetail/ProductDetailActivity.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/widget/CartAddBottomSheet.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/MainViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/UiModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/bottomsheet/BottomSheetViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/CartViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/cart/HistoryViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/BestViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/MainDishViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/main/OtherDishViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderDetailViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/order/OrderListViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
> [RENAME] UiStates -> UiState, UiEvents -> UiEvent 클래스명 수정

- app/src/main/java/co/kr/woowahan_banchan/data/model/local/OrderDto.kt
- app/src/main/java/co/kr/woowahan_banchan/domain/entity/orderhistory/OrderHistory.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/OrderListAdapter.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/cart/CartFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/ui/order/orderdetail/OrderDetailFragment.kt
- app/src/main/java/co/kr/woowahan_banchan/presentation/viewmodel/productdetail/ProductDetailViewModel.kt
- app/src/main/java/co/kr/woowahan_banchan/util/NumberExtension.kt
> [FEATURE] 데모 및 시연을 위한 배송 완료까지 걸리는 시간 20분 -> 10초 변경

- app/src/main/java/co/kr/woowahan_banchan/presentation/adapter/DishAdapter.kt
> [FIX] 카트버튼 이벤트 누락 수정

- app/src/main/java/co/kr/woowahan_banchan/util/ImageLoader.kt
- #213 
close #213 
To. 친애하는 @hansh0101 (A.K.A. Iceman)
우리가 직접 만들고 사용하던 ImageLoader의 치명적인 단점이 존재하고 있음을 깨달아 급하게 수정을 하게되었네 그동안 HashMap을 이용해 메모리 캐싱을 하고 있던 이미지들이 현재는 개수가 많지 않아 큰 문제는 없었지만 이미지가 많아질수록 메모리를 점점 많이 차지하게 될 것이네... 듣기만 해도 무서워지지 않나? 그래서 이 캐시의 데이터를 적당히 관리를 해줄 필요가 느껴져 기존의 HashMap으로 관리하던 것을 안드로이드에서 제공하는 LruCache 로 교체했네 LruCache는 지정한 최대 가능한 메모리 사용량과 LRU(Least Recently Used)알고리즘을 이용해 데이터를 관리하지...
현재는 어플이 할당받은 메모리의 8분에 1(수치로는 12.5%) 정도까지만 사용할 수 있도록 지정해두었다네
From. @Skipancho
> [FEATURE] #213 - ImageLoader 의 캐시를 HashMap에서 LruCache로 변경
